version: 0.2

env:
  secrets-manager:
    SECRET_USERNAME: "pipeline-docker-credentials:username"
    SECRET_PASSWORD: "pipeline-docker-credentials:password"
    AWS_ACCESS_KEY_ID: "pipeline-docker-credentials:access_key" 
    AWS_SECRET_ACCESS_KEY: "pipeline-docker-credentials:secret_key" 

phases:

  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo "Node Version"
      - node -v
      - npm -v
      - echo "showing structure"
      - ls -R
      - echo Logging in to DockerHub
      - echo "$SECRET_PASSWORD" | docker login -u "$SECRET_USERNAME" --password-stdin


  build:
    commands:
      - echo "Building Docker Image..."
      - docker build --platform linux/arm64 -t emilesherrott/pottery-db:latest ./db

  post_build:
    commands:
      - echo "Pushing Docker Image..."
      - docker push emilesherrott/pottery-db:latest
      - cd api
      - npm install
      - npm run test
      - cd ..
      - echo "Installing Terraform..."
      - curl -LO https://releases.hashicorp.com/terraform/1.9.0/terraform_1.9.0_linux_amd64.zip
      - rm -rf terraform
      - unzip -o terraform_1.9.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform version
      - echo "Running Terraform..."
      - pwd
      - ls 
      - cd terraform
      - terraform init
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan


artifacts: 
  files:
    - db/Dockerfile
