version: 0.2

env:
  secrets-manager:
    SECRET_USERNAME: "pipeline-docker-credentials:username"
    SECRET_PASSWORD: "pipeline-docker-credentials:password"

phases:

  install:
    runtime-versions:
      docker: 24
      nodejs: 20
  pre_build:
    commands:
      - echo Logging in to DockerHub
      - echo "$SECRET_PASSWORD" | docker login -u "$SECRET_USERNAME" --password-stdin


  build:
    commands:
      - echo "Building Docker Image..."
      - docker build --platform linux/arm64 -t emilesherrott/pottery-db:latest ./db

  post_build:
    commands:
      - echo "Pushing Docker Image..."
      - docker push emilesherrott/pottery-db:latest

  testing:
    commands:
      - cd api
      - npm install
      - npm run test
      - cd ..

  terraform_installation:
    commands:
      - echo "Installing Terraform..."
      - curl -LO https://releases.hashicorp.com/terraform/1.9.0/terraform_1.9.0_linux_amd64.zip
      - unzip terraform_1.9.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform version
  
  terraform_apply:
    commands:
      - echo "Running Terraform..."
      - cd terraform
      - terraform init
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan


artifacts: 
  files:
    - Dockerfile
